Initial version of unischedule backend: get endpoints
ISIS3510-202410-Team-13/Backend pull request #16
Opened 2024-04-08 01:19 UTC by SnowArtz

Back Implemented in Node.js with the basic endpoints (for now we only have /get that we consider the most important for now but we will update it), the endpoints available for now are:

       1. /user/:id/groups (Get the groups of a User given its ID) 2.
       2. /user/:id/friend (Get the friends of a User given his ID) 
       3. /user/:id/events (Get the events of a User given his ID)
       4. /group/:id/members (Get the members of a Group given its ID)
       5. /group/:id/events (Get the events of a Group given its ID)

2024-04-08 01:34 UTC, jsurrea requested changes
Great work! @SnowArtz @iGotty You rock!

My only suggestion would be to change the directory name. Since we are _kind of_ following a micro-services architecture, it might be misleading to have a directory called `unischedule-backend`. Maybe something more explicit like `UsersGroupsFriends`in the meantime?

Other thing I think would be useful would be to add a Dockerfile! This will enable us to quickly deploy any new version in our VMs. You can take inspiration from [here](https://github.com/ISIS3510-202410-Team-13/Backend/blob/main/AvailableSpaces/Dockerfile), which is also a Dockerfile for Node + Express.

Great job as always!

2024-04-08 23:04 UTC, iGotty approved these changes
Awesome!

2024-04-10 16:25 UTC, SnowArtz commented
Hi @jsurrea! 

Thanks for your comments and your feedback!! Can you check the new changes I have made and look if now it looks good for you?

2024-04-10 18:56 UTC, jsurrea approved these changes

2024-04-10 18:56 UTC, merged